# Generated by Django 2.2 on 2020-07-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('quiz_detail', models.TextField(blank=True, max_length=600)),
                ('quiz_ans_1', models.CharField(choices=[('quiz_ans_01', ''), ('quiz_ans_02', ''), ('quiz_ans_03', ''), ('quiz_ans_04', '')], max_length=50)),
                ('quz_correct_ans', models.IntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lessons')),
            ],
        ),
    ]
