# Generated by Django 2.2 on 2020-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(max_length=150)),
                ('faq_desc', models.TextField()),
                ('vote', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(choices=[('student', ' Student'), ('team', 'Team'), ('enterprise', 'Enterprise')], max_length=20)),
                ('package_desc', models.CharField(max_length=150)),
                ('package_price', models.IntegerField()),
                ('bill_cycle', models.CharField(choices=[('month', ' Month'), ('year', 'Year')], max_length=10)),
                ('package_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
