# Generated by Django 2.2 on 2020-07-22 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.utils_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(default='assets/default_images/no-image.png', upload_to=lms.utils_file.upload_image_path)),
                ('cover_title_not_authenticated', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_text_not_authenticated', models.TextField(blank=True, max_length=400, null=True)),
                ('url_link_not_authenticated', models.CharField(blank=True, choices=[('courses_url', 'LESSONS URL'), ('register_url', 'SIGNUP URL')], max_length=25, null=True)),
                ('url_btn_not_authenticated', models.CharField(blank=True, max_length=25, null=True)),
                ('cover_title_authenticated', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_text_authenticated', models.TextField(blank=True, max_length=400, null=True)),
                ('url_link_authenticated', models.CharField(blank=True, choices=[('courses_url', 'LESSONS URL'), ('register_url', 'SIGNUP URL')], max_length=25, null=True)),
                ('url_btn_authenticated', models.CharField(blank=True, max_length=25, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(default='assets/default_images/no-image.png', upload_to=lms.utils_file.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='assets/default_images/no-image.png', upload_to=lms.utils_file.upload_image_path)),
                ('footer_title', models.CharField(blank=True, max_length=50, null=True)),
                ('footer_description', models.TextField(blank=True, max_length=800, null=True)),
                ('copyright_quote', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='assets/default_images/no-image.png', upload_to=lms.utils_file.upload_image_path)),
                ('header_title', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TopView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.IntegerField(blank=True, default=0, null=True)),
                ('modified', models.DateField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('testimonial', models.TextField(blank=True, max_length=500, null=True, verbose_name='Your feedback')),
                ('visitor_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='Visitor IP')),
                ('visitor_name', models.CharField(max_length=100, null=True, verbose_name='Your name')),
                ('visitor_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Your email')),
                ('visitor_rating', models.CharField(default=5, max_length=2, verbose_name='Your rating out of 5')),
                ('isRegistered', models.BooleanField(default=False)),
                ('modified', models.DateField(auto_now_add=True, null=True)),
                ('feedback_user', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
