# Generated by Django 2.2 on 2020-07-17 11:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import lms.utils_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Category name')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=25, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=200, verbose_name='Sub category name')),
                ('subcategory_short_desc', models.TextField(blank=True, max_length=400, null=True)),
                ('subcategory_long_desc', ckeditor.fields.RichTextField()),
                ('what_u_will_learn', ckeditor.fields.RichTextField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('image', models.ImageField(default='assets/default_images/no-image.png', upload_to=lms.utils_file.upload_image_path)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
